# Generated by Django 3.2.11 on 2022-02-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='report_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.reports'),
        ),
    ]
