# Generated by Django 3.2.11 on 2022-02-07 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_pathology_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cbcreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hb', models.FloatField(blank=True)),
                ('rbc', models.FloatField(blank=True)),
                ('wbc', models.FloatField(blank=True)),
                ('platelet', models.FloatField(blank=True)),
                ('hematocrit', models.FloatField(blank=True)),
                ('mcv', models.FloatField(blank=True)),
                ('mch', models.FloatField(blank=True)),
                ('mchc', models.FloatField(blank=True)),
                ('neutrophils', models.FloatField(blank=True)),
                ('lymphocytes', models.FloatField(blank=True)),
                ('eosinophils', models.FloatField(blank=True)),
                ('monocytes', models.FloatField(blank=True)),
                ('basophils', models.FloatField(blank=True)),
                ('paots', models.CharField(blank=True, max_length=100)),
                ('pfm', models.CharField(blank=True, max_length=100)),
                ('microcytosis', models.CharField(blank=True, max_length=100)),
                ('hyphochromia', models.CharField(blank=True, max_length=100)),
                ('anisocytosis', models.CharField(blank=True, max_length=100)),
                ('report_name', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='user.reports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
